// Donnees MJSL injectees directement — regenerer ce fichier si les GeoJSON sont mis a jour.
// Pour regenerer : coller le contenu JSON de chaque couche dans la variable correspondante.

window.MJSL_DATA = {
  mjsl_segments_cheminement: {"type":"FeatureCollection","name":"mjsl_segments_cheminement","features":[{"type":"Feature","properties":{"seg_id":"VP_VA_001","secteur":"Vieux-Port - Vallon des Auffes","nom_lieu":"Quai de Rive Neuve / debut Corniche","debut":"Vieux-Port","fin":"Anse des Catalans","long_m":900,"date_obs":"","observateur":"","d1_physique":1,"d2_sensoriel":1,"d3_cognitif":1,"d4_economique":1,"d5_social":1,"d6_democratique":0,"score_mjsl":0.83,"classe_mjsl":"faible","cat_fragmentation":1,"cat_metropolitaine":1,"cat_privatisation":1,"photo_id":"","source":"segment pilote a verifier sur terrain","note_obs":"Exemple a remplacer par le releve precis."},"geometry":{"type":"LineString","coordinates":[[5.3698,43.2946],[5.3626,43.2908]]}},{"type":"Feature","properties":{"seg_id":"VA_MA_001","secteur":"Vallon des Auffes - Malmousque","nom_lieu":"Acces Vallon des Auffes et sequences en balcon","debut":"Vallon des Auffes","fin":"Malmousque","long_m":850,"date_obs":"","observateur":"","d1_physique":0,"d2_sensoriel":1,"d3_cognitif":1,"d4_economique":1,"d5_social":1,"d6_democratique":0,"score_mjsl":0.67,"classe_mjsl":"excluant","cat_fragmentation":1,"cat_metropolitaine":1,"cat_privatisation":1,"photo_id":"","source":"segment pilote a verifier sur terrain","note_obs":"Secteur test pertinent pour escaliers, topographie et surcharge sensorielle."},"geometry":{"type":"LineString","coordinates":[[5.3528,43.2864],[5.3482,43.2819]]}},{"type":"Feature","properties":{"seg_id":"CO_001","secteur":"Corniche Kennedy","nom_lieu":"Promenade en balcon sur mer","debut":"Malmousque","fin":"Statue de David","long_m":2800,"date_obs":"","observateur":"","d1_physique":1,"d2_sensoriel":1,"d3_cognitif":1,"d4_economique":2,"d5_social":1,"d6_democratique":0,"score_mjsl":1.0,"classe_mjsl":"faible","cat_fragmentation":1,"cat_metropolitaine":1,"cat_privatisation":0,"photo_id":"","source":"segment pilote a verifier sur terrain","note_obs":"Exemple de troncon long a redecouper en segments de 25 a 50 m."},"geometry":{"type":"LineString","coordinates":[[5.3482,43.2819],[5.3664,43.2622]]}}]},

  mjsl_points_rupture: {"type":"FeatureCollection","name":"mjsl_points_rupture","features":[{"type":"Feature","properties":{"pt_id":"RUP_VA_001","seg_id":"VA_MA_001","secteur":"Vallon des Auffes","type_rupture":"Escaliers concentres","date_obs":"","observateur":"","gravite":3,"dimension_principale":"D1","score_associe":0,"photo_id":"","source":"a verifier sur terrain","note_obs":"Rupture topographique majeure; renseigner nombre exact de marches et alternative."},"geometry":{"type":"Point","coordinates":[5.3528,43.2864]}},{"type":"Feature","properties":{"pt_id":"RUP_CO_001","seg_id":"CO_001","secteur":"Corniche Kennedy","type_rupture":"Retrecissement de trottoir","date_obs":"","observateur":"","gravite":2,"dimension_principale":"D1","score_associe":1,"photo_id":"","source":"a verifier sur terrain","note_obs":"Point modele pour relever largeur utile entre parapet, mobilier et flux routier."},"geometry":{"type":"Point","coordinates":[5.3595,43.2724]}}]},

  mjsl_amenites_repos: {"type":"FeatureCollection","name":"mjsl_amenites_repos","features":[{"type":"Feature","properties":{"amenite_id":"REP_CO_001","seg_id":"CO_001","secteur":"Corniche Kennedy","type_amenite":"Belvedere / appui face mer","gratuit":"oui","accessible":"a verifier","date_obs":"","score_confort":2,"score_gratuite":3,"score_accessibilite":1,"photo_id":"","source":"a verifier sur terrain","note_obs":"Verifier ombre, assise, largeur de manoeuvre et rupture avec le flux."},"geometry":{"type":"Point","coordinates":[5.3609,43.2707]}},{"type":"Feature","properties":{"amenite_id":"REP_VA_001","seg_id":"VA_MA_001","secteur":"Vallon des Auffes","type_amenite":"Assise commerciale","gratuit":"non","accessible":"partiel","date_obs":"","score_confort":2,"score_gratuite":0,"score_accessibilite":1,"photo_id":"","source":"a verifier sur terrain","note_obs":"Exemple pour documenter le confort conditionne a la consommation."},"geometry":{"type":"Point","coordinates":[5.3524,43.2861]}}]},

  mjsl_ambiances: {"type":"FeatureCollection","name":"mjsl_ambiances","features":[{"type":"Feature","properties":{"amb_id":"AMB_CO_001","seg_id":"CO_001","secteur":"Corniche Kennedy","type_ambiance":"Bruit routier continu","moment":"journee","date_obs":"","score_sensoriel":1,"score_cognitif":1,"niveau_db":75,"intensite":"forte","photo_id":"","source":"valeur indicative a mesurer","note_obs":"Mesurer avec application sonometre; noter heure, trafic et possibilite de repos."},"geometry":{"type":"Polygon","coordinates":[[[5.3569,43.2761],[5.3632,43.2694],[5.3641,43.2699],[5.3578,43.2767],[5.3569,43.2761]]]}},{"type":"Feature","properties":{"amb_id":"AMB_VA_001","seg_id":"VA_MA_001","secteur":"Vallon des Auffes","type_ambiance":"Surcharge sensorielle ponctuelle","moment":"soir / weekend","date_obs":"","score_sensoriel":1,"score_cognitif":0,"niveau_db":80,"intensite":"tres forte","photo_id":"","source":"valeur indicative a mesurer","note_obs":"Voix, moteurs, terrasses et espace resserre; verifier zones de retrait."},"geometry":{"type":"Polygon","coordinates":[[[5.3518,43.2869],[5.3533,43.2869],[5.3533,43.2856],[5.3518,43.2856],[5.3518,43.2869]]]}}]},

  mjsl_seuils_legitimite: {"type":"FeatureCollection","name":"mjsl_seuils_legitimite","features":[{"type":"Feature","properties":{"seuil_id":"SEU_VA_001","seg_id":"VA_MA_001","secteur":"Vallon des Auffes","type_seuil":"Terrasse commerciale filtrante","public_prive":"occupation commerciale du public","date_obs":"","score_social":1,"score_economique":0,"gravite":2,"photo_id":"","source":"a verifier sur terrain","note_obs":"Renseigner largeur occupee et largeur gratuite restante."},"geometry":{"type":"Point","coordinates":[5.3522,43.2862]}},{"type":"Feature","properties":{"seuil_id":"SEU_CO_001","seg_id":"CO_001","secteur":"Corniche Kennedy","type_seuil":"Entree avec marches","public_prive":"prive ouvert au public","date_obs":"","score_social":1,"score_economique":2,"gravite":2,"photo_id":"","source":"a verifier sur terrain","note_obs":"Verifier nombre de marches, rampe, interphone, effort visible impose."},"geometry":{"type":"Point","coordinates":[5.3563,43.2768]}}]},

  mjsl_transport_metropolitain: {"type":"FeatureCollection","name":"mjsl_transport_metropolitain","features":[{"type":"Feature","properties":{"tr_id":"TR_NORD_CO_001","origine":"Quartiers nord / exemple","destination":"Corniche Kennedy","mode":"transport public + marche","ligne":"a renseigner","correspondances":2,"date_obs":"","temps_min":60,"cout_eur":1.8,"score_continuite":1,"score_cout":2,"score_lisibilite":1,"source":"itineraire indicatif a verifier avec RTM / terrain","note_obs":"Cette couche sert a montrer que l'accessibilite du littoral commence avant la corniche."},"geometry":{"type":"LineString","coordinates":[[5.3790,43.3350],[5.3740,43.3020],[5.3609,43.2707]]}}]},

  mjsl_participation: {"type":"FeatureCollection","name":"mjsl_participation","features":[{"type":"Feature","properties":{"part_id":"PAR_CO_001","secteur":"Corniche Kennedy","type_dispositif":"Panneau ou information projet","institution":"a renseigner","date_obs":"","score_accessibilite":1,"score_lisibilite":0,"score_reversibilite":0,"photo_id":"","source":"a verifier sur terrain","note_obs":"Verifier hauteur, langage, presence d'une version simplifiee et possibilite de retour usager."},"geometry":{"type":"Point","coordinates":[5.3624,43.2689]}},{"type":"Feature","properties":{"part_id":"PAR_VA_001","secteur":"Vallon des Auffes","type_dispositif":"Trace de concertation absente ou non visible","institution":"a renseigner","date_obs":"","score_accessibilite":0,"score_lisibilite":0,"score_reversibilite":0,"photo_id":"","source":"a verifier sur terrain","note_obs":"Point temoin: documenter aussi l'absence de dispositif visible."},"geometry":{"type":"Point","coordinates":[5.3527,43.2864]}}]}
};
